#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

fail() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required."
}

require_identifier() {
  [[ "$2" =~ ^[0-9a-f]{32}$ ]] || fail "$1 must be a 32-character Cloudflare ID."
}

ensure_bucket() {
  local bucket="$1"
  if bunx wrangler r2 bucket info "$bucket" >/dev/null 2>&1; then
    note "$bucket already exists"
  else
    bunx wrangler r2 bucket create "$bucket" --update-config=false
  fi
}

clear_cors() {
  local bucket="$1"
  local output="$BOOTSTRAP_TEMP/$bucket-cors.txt"
  if ! bunx wrangler r2 bucket cors list "$bucket" >"$output" 2>&1; then
    if grep -Fq 'code: 10059' "$output"; then
      note "$bucket CORS is already empty"
      return
    fi
    sed 's/^/  /' "$output" >&2
    fail "Could not inspect $bucket CORS configuration."
  fi
  if grep -Eqi 'no cors|"rules"[[:space:]]*:[[:space:]]*\[\]|^[[:space:]]*\[[[:space:]]*\][[:space:]]*$' "$output"; then
    note "$bucket CORS is already empty"
  else
    bunx wrangler r2 bucket cors delete "$bucket" --force
  fi
}

remove_custom_domains() {
  local bucket="$1"
  local output="$BOOTSTRAP_TEMP/$bucket-domains.txt"
  local domains="$BOOTSTRAP_TEMP/$bucket-domain-names.txt"
  NO_COLOR=1 bunx wrangler r2 bucket domain list "$bucket" >"$output"
  if grep -Fq 'There are no custom domains connected to this bucket.' "$output"; then
    note "$bucket has no custom domains"
    return
  fi
  awk '/^domain:[[:space:]]*/ { sub(/^domain:[[:space:]]*/, ""); print }' "$output" >"$domains"
  [[ -s "$domains" ]] || fail "Could not inspect the custom domains attached to $bucket."
  while IFS= read -r domain; do
    bunx wrangler r2 bucket domain remove "$bucket" --domain "$domain" --force
  done <"$domains"
}

domain_is_active() {
  local output="$BOOTSTRAP_TEMP/domain.txt"
  bunx wrangler r2 bucket domain get drop-content --domain drop.clay.sh >"$output" 2>/dev/null || return 1
  grep -Eqi 'ownership[^[:alnum:]]+active' "$output" &&
    grep -Eqi 'ssl[^[:alnum:]]+active' "$output"
}

if [[ "${1:-}" == "--check" ]]; then
  require_command bash
  require_command bun
  require_command bunx
  check_directory=$(mktemp -d)
  trap 'rm -rf -- "$check_directory"' EXIT
  bash -n "$0"
  bun run scripts/verify-production.ts --help >/dev/null
  bunx wrangler deploy --dry-run --outdir "$check_directory" >/dev/null
  printf 'Production bootstrap checks passed.\n'
  exit 0
fi

require_command bun
require_command bunx
require_command curl

umask 077
BOOTSTRAP_TEMP=$(mktemp -d)
R2_TOKEN_NEEDS_REVOCATION=0

cleanup_bootstrap() {
  rm -rf -- "$BOOTSTRAP_TEMP"
  if (( R2_TOKEN_NEEDS_REVOCATION )); then
    warn "the temporary R2 token may still be live; revoke it at https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID:-}/r2/api-tokens"
  fi
}

trap cleanup_bootstrap EXIT

banner "Provision drop.clay.sh"

stage "Cloudflare account"
say "Wrangler needs an authenticated Cloudflare session and the clay.sh account IDs."
if bunx wrangler whoami --json >/dev/null 2>&1; then
  note "Wrangler is already authenticated"
else
  step "Approve Wrangler in the browser window that opens."
  bunx wrangler login
fi
open_url "https://dash.cloudflare.com/"
step "Open the account that owns clay.sh. Copy its Account ID from the account overview."
ask CLOUDFLARE_ACCOUNT_ID "Cloudflare Account ID:"
require_identifier "Cloudflare Account ID" "$CLOUDFLARE_ACCOUNT_ID"
export CLOUDFLARE_ACCOUNT_ID
bunx wrangler whoami --account "$CLOUDFLARE_ACCOUNT_ID" --json >/dev/null ||
  fail "Wrangler is not authenticated for that Cloudflare account."
step "Open clay.sh, then copy its Zone ID from the zone overview."
ask CLOUDFLARE_ZONE_ID "clay.sh Zone ID:"
require_identifier "clay.sh Zone ID" "$CLOUDFLARE_ZONE_ID"

stage "R2 buckets"
say "This creates the two production buckets and removes alternate public access."
confirm "Provision drop-control and drop-content in this Cloudflare account?" || fail "Provisioning cancelled."
ensure_bucket drop-control
ensure_bucket drop-content
clear_cors drop-control
clear_cors drop-content
bunx wrangler r2 bucket dev-url disable drop-control --force
bunx wrangler r2 bucket dev-url disable drop-content --force
remove_custom_domains drop-control

stage "Admin Key"
say "The Admin Key is stored outside the repository and prepared as a Worker secret."
DROP_CONFIG_DIRECTORY="${XDG_CONFIG_HOME:-${HOME}/.config}/drop"
ADMIN_KEY_FILE="$DROP_CONFIG_DIRECTORY/admin-key"
mkdir -p "$DROP_CONFIG_DIRECTORY"
chmod 700 "$DROP_CONFIG_DIRECTORY"
if [[ -f "$ADMIN_KEY_FILE" ]]; then
  ADMIN_KEY=$(<"$ADMIN_KEY_FILE")
  [[ "$ADMIN_KEY" =~ ^drop_a_[0-9a-f]{64}$ ]] || fail "$ADMIN_KEY_FILE does not contain a valid Admin Key."
  note "using the existing Admin Key from $ADMIN_KEY_FILE"
else
  ADMIN_KEY=$(bun -e 'const bytes = crypto.getRandomValues(new Uint8Array(32)); process.stdout.write("drop_a_" + Array.from(bytes, byte => byte.toString(16).padStart(2, "0")).join(""))')
  printf '%s' "$ADMIN_KEY" >"$ADMIN_KEY_FILE"
  chmod 600 "$ADMIN_KEY_FILE"
  note "stored the new Admin Key in $ADMIN_KEY_FILE with mode 0600"
fi
printf 'ADMIN_KEY=%s\n' "$ADMIN_KEY" >"$BOOTSTRAP_TEMP/admin.env"

stage "R2 domain and Worker route"
say "drop-content serves Files and Docs. After its DNS record is active, the Worker route takes precedence for /api/*."
if bunx wrangler r2 bucket domain list drop-content | grep -Fq 'drop.clay.sh'; then
  note "drop.clay.sh is already attached to drop-content"
else
  bunx wrangler r2 bucket domain add drop-content \
    --domain drop.clay.sh \
    --zone-id "$CLOUDFLARE_ZONE_ID" \
    --min-tls 1.2 \
    --force
fi
for attempt in {1..40}; do
  if domain_is_active; then
    note "drop.clay.sh ownership and TLS are active"
    break
  fi
  (( attempt == 40 )) && fail "drop.clay.sh did not become active within 10 minutes."
  note "waiting for drop.clay.sh ownership and TLS"
  sleep 15
done
confirm "Deploy the production Worker route and daily cron now?" || fail "Worker deployment cancelled."
bunx wrangler deploy --secrets-file "$BOOTSTRAP_TEMP/admin.env"

stage "Cache rule"
say "Cloudflare must bypass cache for every public File and Doc response."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/clay.sh/caching/cache-rules"
step "Create or edit a Cache Rule named 'Drop public reads do not cache'."
step "Use this expression: (http.host eq \"drop.clay.sh\" and (starts_with(http.request.uri.path, \"/files/\") or starts_with(http.request.uri.path, \"/docs/\")))"
step "Set Cache eligibility to Bypass cache, then deploy the rule."
pause "Press Enter after the cache rule is deployed."

stage "Response headers"
say "Create two response-header rules for public reads. Edit existing rules with these names on a re-run."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/clay.sh/rules/transform-rules/modify-response-header"
step "Create 'Drop public response headers' with the same /files/ and /docs/ expression from the previous stage."
step "Set static Cache-Control=no-store, X-Content-Type-Options=nosniff, Referrer-Policy=no-referrer, and X-Robots-Tag=noindex, nofollow, noarchive. Deploy it."
step "Create 'Drop Doc CSP' matching: (http.host eq \"drop.clay.sh\" and starts_with(http.request.uri.path, \"/docs/\"))"
step "Set static Content-Security-Policy to: default-src 'none'; base-uri 'none'; connect-src 'none'; font-src data: https:; form-action 'none'; frame-ancestors 'none'; frame-src 'none'; img-src data: https:; media-src data: https:; object-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; worker-src 'none'; sandbox allow-scripts allow-popups allow-popups-to-escape-sandbox"
step "Deploy the Doc rule."
pause "Press Enter after both response-header rules are deployed."

stage "Temporary R2 credential"
say "Live expiry verification needs a short-lived credential that can change one test object's metadata."
R2_TOKEN_NEEDS_REVOCATION=1
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/r2/api-tokens"
step "Create an Account API token with Object Read & Write access to drop-content only."
step "Copy the Access Key ID and Secret Access Key. Do not save them in a shell command or repository file."
ask R2_ACCESS_KEY_ID "Temporary R2 Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Temporary R2 Secret Access Key:"
[[ -n "$R2_ACCESS_KEY_ID" && -n "$R2_SECRET_ACCESS_KEY" ]] || fail "Both temporary R2 credential values are required."

stage "Upload Key and live acceptance"
say "This creates the initial Upload Key, configures the local CLI, and exercises the live service."
set +e
(
  set -e
  UPLOAD_KEY_CONFIG="$DROP_CONFIG_DIRECTORY/config.json"
  UPLOAD_KEY=""
  if [[ -f "$UPLOAD_KEY_CONFIG" ]]; then
    UPLOAD_KEY=$(bun -e 'const path = process.argv[1]; try { const value = await Bun.file(path).json(); if (typeof value.uploadKey === "string") process.stdout.write(value.uploadKey); } catch {}' "$UPLOAD_KEY_CONFIG")
  fi
  KEY_LIST=$(DROP_ADMIN_KEY="$ADMIN_KEY" DROP_API_URL="https://drop.clay.sh" bun run src/cli/index.ts admin keys list --json)
  if [[ "$UPLOAD_KEY" =~ ^drop_u_[0-9a-f]{32}_[0-9a-f]{64}$ ]] && grep -Fq "${UPLOAD_KEY:7:32}" <<<"$KEY_LIST"; then
    note "using the Upload Key already configured in the local CLI"
  else
    UPLOAD_KEY=$(DROP_ADMIN_KEY="$ADMIN_KEY" DROP_API_URL="https://drop.clay.sh" bun run src/cli/index.ts admin keys create)
  fi
  [[ "$UPLOAD_KEY" =~ ^drop_u_[0-9a-f]{32}_[0-9a-f]{64}$ ]] || fail "The live Admin interface returned an invalid Upload Key."
  printf '%s' "$UPLOAD_KEY" | bun run src/cli/index.ts auth set
  DROP_ADMIN_KEY="$ADMIN_KEY" \
  DROP_UPLOAD_KEY="$UPLOAD_KEY" \
  R2_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
  R2_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID" \
  R2_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY" \
  bun run verify:production
)
ACCEPTANCE_STATUS=$?
set -e

stage "Revoke the temporary credential"
say "The R2 credential is no longer needed. Revoking it also invalidates any derived credentials."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/r2/api-tokens"
step "Find the temporary drop-content token created in stage 7 and revoke it."
confirm "Has the temporary R2 token been revoked?" || fail "Revoke the temporary R2 token before completing bootstrap."
R2_TOKEN_NEEDS_REVOCATION=0
unset R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY
(( ACCEPTANCE_STATUS == 0 )) || fail "Live acceptance failed; the temporary token was revoked safely."

stage "Production logs"
say "Inspect the custom Drop events from the acceptance run."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/workers/services/view/drop/production/observability/logs"
step "Open a recent custom event. Its application fields must be timestamp, credentialId, url, kind, size, retention, outcome, and status only."
step "Confirm there is no Worker Logpush or Tail Worker sink and no application rate limiter."
confirm "Do the logs and production settings match?" || fail "Production log verification was not confirmed."

say "The initial Upload Key is configured in the local CLI."
say "The Admin Key remains at $ADMIN_KEY_FILE and was not written to this repository or shell history."
unset ADMIN_KEY UPLOAD_KEY

finish
