#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=0

fail() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required."
}

if [[ "${1:-}" == "--check" ]]; then
  require_command bash
  require_command bun
  require_command bunx
  check_directory=$(mktemp -d)
  trap 'rm -rf -- "$check_directory"' EXIT
  bash -n "$0"
  if command -v terraform >/dev/null 2>&1; then
    terraform fmt -check -recursive infra/terraform >/dev/null
    if [[ -d infra/terraform/.terraform ]]; then
      terraform -chdir=infra/terraform validate >/dev/null
    fi
  fi
  bun run scripts/ensure-control-bucket-private.ts --help >/dev/null
  bun run scripts/ensure-r2-cors-disabled.ts --help >/dev/null
  bun run scripts/ensure-workers-subdomain.ts --help >/dev/null
  bun run scripts/r2-verification-token.ts --help >/dev/null
  bun run scripts/verify-production.ts --help >/dev/null
  bunx wrangler deploy --dry-run --outdir "$check_directory" >/dev/null
  printf 'Production bootstrap checks passed.\n'
  exit 0
fi

MODE="provision"
if [[ "${1:-}" == "--verify" ]]; then
  MODE="verify"
  shift
fi

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  if [[ "$MODE" == "verify" ]]; then
    printf 'Usage: bun run verify:production\n\nRuns live acceptance without changing Terraform-managed infrastructure.\n'
  else
    printf 'Usage: bun run provision\n\nProvisions Cloudflare, deploys the Worker, and creates the initial Upload Key.\n'
  fi
  exit 0
fi

[[ $# -eq 0 ]] || fail "Unknown argument: $1"

require_command bun
if [[ "$MODE" == "provision" ]]; then
  require_command bunx
  require_command terraform
fi

umask 077
BOOTSTRAP_TEMP=$(mktemp -d)
R2_TOKEN_ID=""

cleanup_bootstrap() {
  if [[ -n "$R2_TOKEN_ID" && -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    warn "revoking the short-lived R2 verification token after an interrupted run"
    bun run scripts/r2-verification-token.ts revoke "$R2_TOKEN_ID" >/dev/null 2>&1 ||
      warn "automatic R2 token revocation failed; it expires within two hours"
  fi
  rm -rf -- "$BOOTSTRAP_TEMP"
}

trap cleanup_bootstrap EXIT

CLOUDFLARE_ACCOUNT_ID="6e0cccdd787599d868ec17156c8d372f"
export CLOUDFLARE_ACCOUNT_ID
DROP_CONFIG_DIRECTORY="${XDG_CONFIG_HOME:-${HOME}/.config}/drop"
ADMIN_KEY_FILE="$DROP_CONFIG_DIRECTORY/admin-key"
UPLOAD_KEY_CONFIG="$DROP_CONFIG_DIRECTORY/config.json"

if [[ "$MODE" == "verify" ]]; then
  TOTAL_STAGES=3
  banner "Verify drop.clay.sh production"

  stage "Cloudflare verification token"
  say "Verification uses this token only to create and revoke a two-hour, drop-content-only credential."
  note "Reuse the active provisioning token, or create a token with Account API Tokens Edit for the clay.sh account."
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  ask_secret CLOUDFLARE_API_TOKEN "Temporary Cloudflare API token:"
  [[ -n "$CLOUDFLARE_API_TOKEN" ]] || fail "The Cloudflare API token is required."
  export CLOUDFLARE_API_TOKEN
  # JavaScript reads the token from process.env at runtime.
  # shellcheck disable=SC2016
  bun -e 'const response = await fetch("https://api.cloudflare.com/client/v4/user/tokens/verify", { headers: { Authorization: `Bearer ${process.env.CLOUDFLARE_API_TOKEN}` } }); const body = await response.json(); if (!response.ok || body.success !== true) process.exit(1)' ||
    fail "Cloudflare rejected that API token."

  stage "Live acceptance"
  say "This creates temporary Drops and credentials. It does not run Terraform, deploy Worker code, or change Worker triggers."
  [[ -f "$ADMIN_KEY_FILE" ]] || fail "Run bun run provision first; $ADMIN_KEY_FILE does not exist."
  ADMIN_KEY=$(<"$ADMIN_KEY_FILE")
  [[ "$ADMIN_KEY" =~ ^drop_a_[0-9a-f]{64}$ ]] || fail "$ADMIN_KEY_FILE does not contain a valid Admin Key."
  [[ -f "$UPLOAD_KEY_CONFIG" ]] || fail "Run bun run provision first; the local CLI has no Upload Key."
  UPLOAD_KEY=$(bun -e 'const path = process.argv[1]; try { const value = await Bun.file(path).json(); if (typeof value.uploadKey === "string") process.stdout.write(value.uploadKey); } catch {}' "$UPLOAD_KEY_CONFIG")
  [[ "$UPLOAD_KEY" =~ ^drop_u_[0-9a-f]{32}_[0-9a-f]{64}$ ]] || fail "$UPLOAD_KEY_CONFIG does not contain a valid Upload Key."

  bun run scripts/r2-verification-token.ts create "$BOOTSTRAP_TEMP/r2.env"
  # The token helper creates this env file immediately before it is sourced.
  # shellcheck disable=SC1091
  source "$BOOTSTRAP_TEMP/r2.env"
  export R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY
  set +e
  DROP_ADMIN_KEY="$ADMIN_KEY" \
  DROP_UPLOAD_KEY="$UPLOAD_KEY" \
  R2_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
  R2_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID" \
  R2_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY" \
  bun run scripts/verify-production.ts 2>&1 | tee "$BOOTSTRAP_TEMP/acceptance.log"
  ACCEPTANCE_STATUS=${PIPESTATUS[0]}
  set -e

  bun run scripts/r2-verification-token.ts revoke "$R2_TOKEN_ID"
  R2_TOKEN_ID=""
  unset R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY

  stage "Production confirmation"
  CONFIRMATION_STATUS=0
  if (( ACCEPTANCE_STATUS == 0 )); then
    say "Inspect the custom Drop events from the acceptance run."
    open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/workers/services/view/drop/production/observability/logs"
    step "Open a recent custom event. Its application fields must be timestamp, credentialId, url, kind, size, retention, outcome, and status only."
    step "Confirm there is no Worker Logpush or Tail Worker sink and no application rate limiter."
    confirm "Do the logs and production settings match?" || CONFIRMATION_STATUS=$?
  else
    warn "Live acceptance failed. The short-lived R2 token was revoked safely."
    say "The verifier's final output was:"
    tail -n 20 "$BOOTSTRAP_TEMP/acceptance.log"
  fi
  say "The temporary Cloudflare token is no longer needed."
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  step "Revoke 'Drop Terraform bootstrap', or the verification token you created."
  confirm "Has the temporary Cloudflare token been revoked?" || fail "Revoke the temporary Cloudflare token before completing verification."

  (( ACCEPTANCE_STATUS == 0 )) || fail "Live acceptance failed."
  (( CONFIRMATION_STATUS == 0 )) || fail "Production log verification was not confirmed."

  unset ADMIN_KEY UPLOAD_KEY CLOUDFLARE_API_TOKEN
  finish
  exit 0
fi

TOTAL_STAGES=5
banner "Provision drop.clay.sh with Terraform"

stage "Cloudflare provisioning token"
say "Terraform needs one temporary token. It stays in this process and is never written to disk or Terraform state."
note "If a previous run failed and its token is still active, reuse that token."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Select Create Token, then Create Custom Token. Name it 'Drop Terraform bootstrap'."
step "Add Account permissions for Account API Tokens Edit, Workers Scripts Edit, and Workers R2 Storage Edit. Scope them to the clay.sh account."
step "Add Zone permissions for Workers Routes Edit, Cache Rules Edit, Transform Rules Edit, and Zone Read. Scope them to clay.sh only."
step "Set the token to expire tomorrow, create it, and copy its value."
ask_secret CLOUDFLARE_API_TOKEN "Temporary Cloudflare API token:"
[[ -n "$CLOUDFLARE_API_TOKEN" ]] || fail "The Cloudflare API token is required."
export CLOUDFLARE_API_TOKEN
# JavaScript reads the token from process.env at runtime.
# shellcheck disable=SC2016
bun -e 'const response = await fetch("https://api.cloudflare.com/client/v4/user/tokens/verify", { headers: { Authorization: `Bearer ${process.env.CLOUDFLARE_API_TOKEN}` } }); const body = await response.json(); if (!response.ok || body.success !== true) process.exit(1)' ||
  fail "Cloudflare rejected that API token."

stage "Admin Key"
say "The Admin Key is stored outside the repository and prepared as a Worker secret."
mkdir -p "$DROP_CONFIG_DIRECTORY"
chmod 700 "$DROP_CONFIG_DIRECTORY"
if [[ -f "$ADMIN_KEY_FILE" ]]; then
  ADMIN_KEY=$(<"$ADMIN_KEY_FILE")
  [[ "$ADMIN_KEY" =~ ^drop_a_[0-9a-f]{64}$ ]] || fail "$ADMIN_KEY_FILE does not contain a valid Admin Key."
  note "using the existing Admin Key from $ADMIN_KEY_FILE"
else
  ADMIN_KEY=$(bun -e 'const bytes = crypto.getRandomValues(new Uint8Array(32)); process.stdout.write("drop_a_" + Array.from(bytes, byte => byte.toString(16).padStart(2, "0")).join(""))')
  printf '%s' "$ADMIN_KEY" >"$ADMIN_KEY_FILE"
  chmod 600 "$ADMIN_KEY_FILE"
  note "stored the new Admin Key in $ADMIN_KEY_FILE with mode 0600"
fi
printf 'ADMIN_KEY=%s\n' "$ADMIN_KEY" >"$BOOTSTRAP_TEMP/admin.env"

stage "Terraform infrastructure"
say "Terraform adopts the buckets, route, cron, and subdomain from the earlier runs, then creates the cache and response-header rules."
terraform -chdir=infra/terraform init
terraform -chdir=infra/terraform plan -out="$BOOTSTRAP_TEMP/production.tfplan"
confirm "Apply this Terraform plan to the live clay.sh account?" || fail "Terraform apply cancelled."
terraform -chdir=infra/terraform apply "$BOOTSTRAP_TEMP/production.tfplan"

stage "Worker deployment"
say "Wrangler uploads only Worker code, bindings, observability settings, and the Admin Key. Terraform owns its route and cron."
confirm "Deploy the production Worker now?" || fail "Worker deployment cancelled."
bunx wrangler deploy --secrets-file "$BOOTSTRAP_TEMP/admin.env"

stage "Initial Upload Key"
say "The Worker creates the initial Upload Key and stores it in the local Drop CLI configuration."
UPLOAD_KEY=""
if [[ -f "$UPLOAD_KEY_CONFIG" ]]; then
  UPLOAD_KEY=$(bun -e 'const path = process.argv[1]; try { const value = await Bun.file(path).json(); if (typeof value.uploadKey === "string") process.stdout.write(value.uploadKey); } catch {}' "$UPLOAD_KEY_CONFIG")
fi
KEY_LIST=$(DROP_ADMIN_KEY="$ADMIN_KEY" DROP_API_URL="https://drop.clay.sh" bun run src/cli/index.ts admin keys list --json)
if [[ "$UPLOAD_KEY" =~ ^drop_u_[0-9a-f]{32}_[0-9a-f]{64}$ ]] && grep -Fq "${UPLOAD_KEY:7:32}" <<<"$KEY_LIST"; then
  note "using the Upload Key already configured in the local CLI"
else
  UPLOAD_KEY=$(DROP_ADMIN_KEY="$ADMIN_KEY" DROP_API_URL="https://drop.clay.sh" bun run src/cli/index.ts admin keys create)
fi
[[ "$UPLOAD_KEY" =~ ^drop_u_[0-9a-f]{32}_[0-9a-f]{64}$ ]] || fail "The live Admin interface returned an invalid Upload Key."
printf '%s' "$UPLOAD_KEY" | bun run src/cli/index.ts auth set

say "Provisioning is complete. Run bun run verify:production next."
note "Keep the temporary Cloudflare token until verification succeeds."
say "The Admin Key remains at $ADMIN_KEY_FILE and was not written to this repository or shell history."
unset ADMIN_KEY UPLOAD_KEY CLOUDFLARE_API_TOKEN

finish
